name: Generate and Deploy Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Thêm permissions để GitHub Actions có thể deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Doxygen and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz plantuml
    
    - name: Create output directory
      run: |
        mkdir -p docs
    
    - name: Generate Documentation
      run: |
        doxygen Doxyfile
    
    - name: List generated files (debug)
      run: |
        ls -la docs/
        if [ -d "docs/html" ]; then
          ls -la docs/html/
        fi
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/html
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4